"use client";
import { useEffect, useMemo, useState } from "react";
type CountyRow={code:string;name:string;sourceUrl:string;status:"live"|"unavailable";registered:number;ballots:number;turnout:number;mail:number;early:number;electionDay:number;dem:number;rep:number;npa:number;other:number;updated:string|null};
type Payload={generatedAt:string;electionName:string;electionDate:string;counties:CountyRow[]};
type SortKey="name"|"ballots"|"turnout"|"dem"|"rep"|"margin"|"updated";
const number=new Intl.NumberFormat("en-US");
const pct=(v:number)=>`${v.toFixed(2)}%`;
const formatTime=(v:string|null)=>v?new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit",timeZone:"America/New_York",timeZoneName:"short"}).format(new Date(v)):"—";
export default function Home(){
 const[data,setData]=useState<Payload|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[sort,setSort]=useState<SortKey>("ballots"),[ascending,setAscending]=useState(false);
 async function refresh(){setLoading(true);setError("");try{const r=await fetch(`/api/turnout?t=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error("The official feed did not respond.");setData(await r.json())}catch(e){setError(e instanceof Error?e.message:"Unable to load turnout.")}finally{setLoading(false)}}
 useEffect(()=>{refresh();const t=setInterval(refresh,300000);return()=>clearInterval(t)},[]);
 const live=data?.counties.filter(c=>c.status==="live")??[];
 const totals=useMemo(()=>live.reduce((a,c)=>({registered:a.registered+c.registered,ballots:a.ballots+c.ballots,mail:a.mail+c.mail,early:a.early+c.early,electionDay:a.electionDay+c.electionDay,dem:a.dem+c.dem,rep:a.rep+c.rep,npa:a.npa+c.npa,other:a.other+c.other}),{registered:0,ballots:0,mail:0,early:0,electionDay:0,dem:0,rep:0,npa:0,other:0}),[live]);
 const rows=useMemo(()=>{const f=(data?.counties??[]).filter(c=>c.name.toLowerCase().includes(query.toLowerCase())||c.code.toLowerCase().includes(query.toLowerCase()));return f.sort((a,b)=>{const av=sort==="margin"?a.dem-a.rep:a[sort],bv=sort==="margin"?b.dem-b.rep:b[sort];return(typeof av==="string"?av.localeCompare(String(bv)):(Number(av)||0)-(Number(bv)||0))*(ascending?1:-1)})},[data,query,sort,ascending]);
 const partyTotal=totals.dem+totals.rep+totals.npa+totals.other||1;
 function chooseSort(k:SortKey){if(sort===k)setAscending(!ascending);else{setSort(k);setAscending(k==="name")}}
 const SortButton=({k,children}:{k:SortKey,children:React.ReactNode})=><button onClick={()=>chooseSort(k)}>{children}<span>{sort===k?(ascending?"↑":"↓"):""}</span></button>;
 return <main><header className="hero"><div className="brand-lockup"><img src="/vanessa-brito.jpg" alt="Vanessa Brito, 305 Data Girl"/><div><div className="brand-name"><b>305</b> Data Girl</div><div className="brand-tagline">Florida politics—with receipts.</div></div></div><div className="eyebrow"><span className="live-dot"/> OFFICIAL COUNTY REPORTING</div><h1>Florida Live Voter Turnout</h1><p>All 67 counties. One live view. Built from Florida’s county Turnout Quick View reporting feed.</p><div className="status-row"><span>{data?.electionName||"2026 Primary Election"}</span><i/><span>{live.length}/67 counties reporting</span><i/><span>Updated {formatTime(data?.generatedAt??null)}</span><button className="refresh" onClick={refresh} disabled={loading}>{loading?"Refreshing…":"Refresh now"}</button></div></header>
 <section className="content">{error&&<div className="error">{error}<button onClick={refresh}>Try again</button></div>}
 <div className="cards"><article><label>Ballots cast</label><strong>{number.format(totals.ballots)}</strong><small>{totals.registered?pct(totals.ballots/totals.registered*100):"—"} statewide turnout</small></article><article><label>Active eligible voters</label><strong>{number.format(totals.registered)}</strong><small>Across reporting counties</small></article><article><label>Vote by mail</label><strong>{number.format(totals.mail)}</strong><small>{totals.ballots?pct(totals.mail/totals.ballots*100):"—"} of ballots</small></article><article><label>Early voting</label><strong>{number.format(totals.early)}</strong><small>{totals.ballots?pct(totals.early/totals.ballots*100):"—"} of ballots</small></article></div>
 <div className="party-panel"><div><span>DEM</span><strong>{number.format(totals.dem)}</strong><small>{pct(totals.dem/partyTotal*100)}</small></div><div><span>REP</span><strong>{number.format(totals.rep)}</strong><small>{pct(totals.rep/partyTotal*100)}</small></div><div><span>NPA</span><strong>{number.format(totals.npa)}</strong><small>{pct(totals.npa/partyTotal*100)}</small></div><div><span>OTHER</span><strong>{number.format(totals.other)}</strong><small>{pct(totals.other/partyTotal*100)}</small></div><div className="margin"><span>STATEWIDE D–R MARGIN</span><strong className={totals.dem>=totals.rep?"blue":"red"}>{totals.dem>=totals.rep?"D":"R"} +{number.format(Math.abs(totals.dem-totals.rep))}</strong><small>{pct(Math.abs(totals.dem-totals.rep)/partyTotal*100)} of ballots</small></div></div>
 <section className="table-card"><div className="table-head"><div><h2>County scoreboard</h2><p>Click any county to open its official report.</p></div><input aria-label="Search counties" placeholder="Search county or code…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="table-wrap"><table><thead><tr><th><SortButton k="name">County</SortButton></th><th><SortButton k="ballots">Ballots</SortButton></th><th><SortButton k="turnout">Turnout</SortButton></th><th><SortButton k="dem">DEM</SortButton></th><th><SortButton k="rep">REP</SortButton></th><th>NPA</th><th><SortButton k="margin">D–R margin</SortButton></th><th><SortButton k="updated">Last county update</SortButton></th></tr></thead><tbody>{rows.map(c=><tr key={c.code} className={c.status!=="live"?"offline":""}><td><a href={c.sourceUrl} target="_blank" rel="noreferrer"><b>{c.name}</b><span>{c.code} ↗</span></a></td>{c.status==="live"?<><td>{number.format(c.ballots)}</td><td><b>{pct(c.turnout)}</b></td><td className="dem">{number.format(c.dem)}</td><td className="rep">{number.format(c.rep)}</td><td>{number.format(c.npa)}</td><td className={c.dem>=c.rep?"dem":"rep"}>{c.dem>=c.rep?"D":"R"} +{number.format(Math.abs(c.dem-c.rep))}</td><td>{formatTime(c.updated)}</td></>:<td colSpan={7}>Feed unavailable</td>}</tr>)}</tbody></table></div></section>
 <footer><div className="footer-brand"><strong>305 Data Girl</strong><span>Florida politics—with receipts.</span></div><div className="socials"><a href="https://www.instagram.com/vanesabritomiami" target="_blank" rel="noreferrer">Instagram @vanesabritomiami</a><span>Facebook Vanessa Brito</span><a href="https://www.threads.net/@vanessabritomiami" target="_blank" rel="noreferrer">Threads @vanessabritomiami</a><a href="https://x.com/vanessabritomia" target="_blank" rel="noreferrer">X @vanessabritomia</a></div><p>Sources: Florida county Turnout Quick View reports; Broward County’s official ElectionLink reporting widget. Figures are unofficial and update when county election offices publish new data. Dashboard refreshes automatically every five minutes.</p></footer></section></main>
}
