import snapshot from '../../public/data/general-official-snapshot.json';
import districts from '../../public/data/general-districts-congressional.json';
import styles from './general.module.css';
const n=(v:number)=>v.toLocaleString('en-US');
const pct=(v:number)=>v.toFixed(2)+'%';
export default function VbmUpdate(){
 const t=snapshot.totals,b=snapshot.baseline,sent=t.provided.total+t.voted.total,dade=snapshot.counties.find(c=>c.code==='DAD')!;
 return <section className={styles.tableCard} aria-label="October 3 VBM update">
 <div className={styles.tableHead}><div><h2>October 3 VBM update</h2><p>{snapshot.snapshotNotice}</p><p>District voter file: October 3 package, activity through October 2. District figures remain tied to that package when the live official compilation changes.</p></div></div>
 <div className={styles.cards}>
 <article><label>Returned statewide</label><strong>{n(t.voted.total)}</strong><small>{pct(t.voted.total/sent*100)} of {n(sent)} provided • +{n(t.voted.total-b.returned)} since Oct. 2</small></article>
 <article><label>D–R return margin</label><strong>D +{n(t.voted.dem-t.voted.rep)}</strong><small>Widened by {n((t.voted.dem-t.voted.rep)-(b.demReturned-b.repReturned))}</small></article>
 <article><label>Miami-Dade returned</label><strong>{n(dade.voted.total)}</strong><small>{pct(dade.voted.total/(dade.provided.total+dade.voted.total)*100)} • +3,006 since Oct. 2</small></article>
 <article><label>Miami-Dade margin</label><strong>D +{n(dade.voted.dem-dade.voted.rep)}</strong><small>Widened by 268 • {n(dade.provided.total+dade.voted.total)} provided</small></article>
 </div>
 <div className={styles.tableWrap}><table><thead><tr><th>Party</th><th>Provided statewide</th><th>Returned</th><th>Return rate</th><th>Additional returns</th><th>Miami-Dade returns</th></tr></thead><tbody>{(['dem','rep','npa','other'] as const).map(p=><tr key={p}><td>{p.toUpperCase()}</td><td>{n(t.provided[p]+t.voted[p])}</td><td>{n(t.voted[p])}</td><td>{pct(t.voted[p]/(t.provided[p]+t.voted[p])*100)}</td><td>+{n(t.voted[p]-b[`${p}Returned`])}</td><td>{n(dade.voted[p])}</td></tr>)}</tbody></table></div>
 <div className={styles.tableHead}><div><h2>FL-27 and FL-28</h2><p>October 3 voter-level snapshot. Daily changes compare the October 2 package using the same P + V denominator and V return definition.</p></div></div>
 <div className={styles.tableWrap}><table><thead><tr><th>District</th><th>Provided</th><th>Returned</th><th>Daily change</th><th>Return rate</th><th>D–R margin</th><th>NPA share</th><th>Overall rank</th></tr></thead><tbody>{districts.filter(r=>['27','28'].includes(r.district)).map(r=><tr key={r.district}><td>FL-{r.district}</td><td>{n(r.sent)}</td><td>{n(r.returned)}</td><td>+{n(r.changeReturned)}</td><td>{pct(r.returnRate)}</td><td>{r.drReturnMargin>=0?'D':'R'} +{n(Math.abs(r.drReturnMargin))}</td><td>{pct(r.npaShare)}</td><td>#{r.overallRank} / 28</td></tr>)}</tbody></table></div>
 <div className={styles.tableWrap}><table><thead><tr><th>District / party</th><th>Provided</th><th>Returned</th><th>Return rate</th><th>Statewide rate rank</th><th>Republican-held peer rank</th></tr></thead><tbody>{districts.filter(r=>['27','28'].includes(r.district)).flatMap(r=>(['dem','rep','npa','other'] as const).map(p=><tr key={r.district+p}><td>FL-{r.district} {p.toUpperCase()}</td><td>{n(r[`${p}Sent`])}</td><td>{n(r[`${p}Returned`])}</td><td>{pct(r[`${p}Rate`])}</td><td>#{r[`${p}Rank`]} / 28</td><td>#{r[`${p}PeerRank`]} / 20</td></tr>))}</tbody></table></div>
 <div className={styles.tableHead}><div>{districts.filter(r=>['27','28'].includes(r.district)).map(r=><p key={r.district}><b>FL-{r.district}:</b> {n(r.demReturned)} Democratic, {n(r.repReturned)} Republican, {n(r.npaReturned)} NPA and {n(r.otherReturned)} Other returns. Democratic conversion is {pct(r.demRate)} versus {pct(r.repRate)} Republican, a {(r.demRate-r.repRate).toFixed(2)}-point D–R gap. The returned-ballot margin changed by {r.changeMargin>=0?'+':''}{n(r.changeMargin)}; return rate rose {r.changeRate.toFixed(2)} points. {r.drSentMargin>0?`Democrats have ${n(r.drSentMargin)} more provided ballots than Republicans, so the raw margin also reflects the composition of the mail pool.`:'The party mix of provided ballots also affects the raw margin.'}</p>)}<p><b>Comparison:</b> FL-27 has a Republican return margin of R+36 despite a Democratic provided-ballot advantage of 6,013. Republican conversion leads by 2.15 points. FL-28 has a much smaller Democratic provided-ballot advantage of 431 and a D+65 return margin, with conversion nearly even (D+0.11 points). FL-28 ranks third statewide overall and first in the current Republican-held district-number peer group; FL-27 ranks fourth and second.</p><p><b>Reporting status:</b> Baker, Gulf, Lafayette and Liberty report zero returns; Jackson reports one. Pinellas reports 536 / 205,072 provided (0.26%), while Pasco reports 6,357 / 51,903 (12.25%). These are reported processing totals; early district rankings can reflect delivery and reporting timing. They do not measure candidate votes or establish enthusiasm.</p><p><b>Comparisons:</b> Statewide changes use the official October 2 aggregate. District changes use the October 2 voter file, which has one fewer statewide V record than that official aggregate. County-level and district-level snapshots are never substituted for one another. Florida can refresh at noon, 3 PM and 6 PM for late county reporting.</p><p><a href={snapshot.sourceUrl} target="_blank" rel="noreferrer">Official Florida data</a> • <a href="/general/districts">All district breakdowns and rankings</a></p></div></div>
 </section>;
}
